---
galaxy_info:
  role_name: ansible_packer
  author: Marko Myllynen <myllynen@redhat.com>
  company: Red Hat, Inc.
  description: ansible_packer role
  license: GPLv3+
  min_ansible_version: "2.14"
  platforms:
    - name: EL
      versions:
        - "7"
        - "8"
        - "9"
    - name: Fedora
      versions:
        - all
    - name: Windows
      versions:
        - "2019"
        - "2022"
  galaxy_tags:
    - packer
    - build
    - image
    - rhel
    - centos
    - fedora
    - windows
dependencies: []
