---
- name: Build custom ISO
  hosts: all
  vars:
    #
    # Base configuration
    #
    # Using packer_ variables for compatibility,
    # genisoimage not Packer used to build image
    packer_builder: iso
    packer_target: rhel_9_2
    packer_target_pretty: Custom RHEL 9.2
    image_name: custom.iso

    # Build options
    do_cleanup: true
    use_force: false

    #
    # OS configuration
    #
    boot_password: "{{ image_password }}"
    root_password: "{{ image_password }}"
    # Autopartitioning does not support
    # creating BIOS/UEFI-compatible images
    bios_uefi_boot: true
    # One of: auto/custom/default/single
    partitioning: default
    disable_ipv6: true
    selinux: enforcing
    #fips_enable: true
    #security_profile: cis
    boot_parameters: net.ifnames.prefix=net quiet systemd.show_status=yes

    # hostname not used with ISO, set the ip= boot parameter instead
    ntp_servers: time.cloudflare.com
    timezone: Europe/Helsinki
    keyboard: fi

    create_admin: true
    admin_user:
      uid: 4444
      gid: 4444
      name: admin
      group: admin
      groups: wheel
      home: /home/admin
      gecos: Admin User
      #ssh_key: "ssh-rsa ... admin@image"
      passwordless_sudo: true

    root_permit_local: true
    root_permit_ssh: "prohibit-password"
    root_permit_override_security_policy: false
    #root_ssh_key: "ssh-rsa ... root@image"

    #
    # Builder configurations
    #

    # Builder: ISO (not a Packer builder)
    # Set ip= to create fully automated ISO for one particular server only
    # Use 'ip=' for generic ISO and require typing IP info on boot from ISO
    iso_boot_parameters: inst.geoloc=0 ip=192.168.122.123::192.168.122.1:255.255.255.0:server.example.com:net0:none
    output_directory: /tmp/iso_images

    #
    # OS installer configuration
    #
    iso:
      rhel_8_8:
        url: file:///VirtualMachines/boot/rhel-8.8-x86_64-dvd.iso
        checksum: sha256:517abcc67ee3b7212f57e180f5d30be3e8269e7a99e127a3399b7935c7e00a09
      rhel_9_2:
        url: file:///VirtualMachines/boot/rhel-9.2-x86_64-dvd.iso
        checksum: sha256:a18bf014e2cb5b6b9cee3ea09ccfd7bc2a84e68e09487bb119a98aa0e3563ac2

  roles:
    - myllynen.ansible_packer.ansible_packer
