---
- name: Build custom Windows UEFI ISO
  hosts: all
  vars:
    #
    # Base configuration
    #
    # Using packer_ variables for compatibility,
    # xorrisofs not Packer is used to build image
    packer_builder: iso
    packer_target: win_2k25
    image_name: custom_w2k25.iso
    win_iso_volume_id: WINDOWS_SERVER_2025

    # Windows OS edition to install from the ISO
    # Interactive installation will show editions
    # The index reference should be either INDEX or NAME
    #win_os_index: INDEX
    #win_os_edition: 2

    # Full path for additional drivers for the target Windows version
    # define only if these are needed on the installation target HW
    win_drivers_path: /tmp/drivers

    # Build options
    do_cleanup: true
    use_force: false

    #
    # OS configuration
    #
    # Password for Windows Administrator and remote management
    # account that will be created during installation, see below.
    # NB! This variable is used to determine whether to build RHEL
    #     or Windows ISOs/VMs and for building RHEL must be unset.
    win_admin_password: "{{ image_password }}"

    # Either bios, uefi, or custom
    # See below for custom example
    win_partitioning: uefi

    win_timezone: FLE Standard Time

    # System locale setting
    win_locale_system: en-US
    # UI locale setting
    win_locale_ui: en-US
    # User locale setting
    win_locale_user: en-US
    # Input locale (language and keyboard) setting, see
    # https://learn.microsoft.com/en-us/windows-hardware/manufacture/desktop/default-input-locales-for-windows-language-packs
    win_locale_input: 0409:0000040B

    #win_product_key:
    win_registered_owner: "Ansible Packer"
    win_registered_organization: "Test Department"

    #win_admin_ssh_key: ssh-ed25519 ... id_ed25519.pub

    # Customization script, runs before enabling remote access
    win_customize_script: |
      # Set system location
      # https://docs.microsoft.com/windows/win32/intl/table-of-geographical-locations
      #Set-WinHomeLocation -GeoId 77
      # Disable IPv6
      Get-NetAdapter | Disable-NetAdapterBinding -ComponentID ms_tcpip6
      # Disable NetBIOS
      $i = 'HKLM:\SYSTEM\CurrentControlSet\Services\NetBT\Parameters\Interfaces'
      Get-ChildItem $i | % {
        Set-ItemProperty -Path "$i\$($_.pschildname)" -Name NetbiosOptions -Value 2
      }
      # Don't display last user name
      $p = 'HKLM:\SOFTWARE\Microsoft\Windows\CurrentVersion\Policies\System'
      Set-ItemProperty -Path $p -Name DontDisplayLastUserName -Type DWord -Value 1 -Force

    #
    # Builder configurations
    #

    # Builder: ISO (not a Packer builder)
    output_directory: /tmp/iso_images

    #
    # OS installer configuration
    #
    iso:
      win_2k25:
        url: file:///VirtualMachines/boot/SERVER_EVAL_x64FRE_en-us-26100.iso
        checksum: "none"

  roles:
    - myllynen.ansible_packer.ansible_packer
