---
- name: Build custom ISO
  hosts: all
  vars:
    #
    # Base configuration
    #
    # Using packer_ variables for compatibility,
    # xorrisofs not Packer is used to build image
    packer_builder: iso
    packer_target: rhel_9_6
    packer_target_pretty: Custom RHEL 9.6
    image_name: custom.iso

    # Build options
    do_cleanup: true
    use_force: false

    #
    # OS configuration
    #
    boot_password: "{{ image_password }}"
    root_password: "{{ image_password }}"

    # Autopartitioning does not support
    # creating BIOS/UEFI-compatible images
    bios_uefi_boot: true
    # One of: auto/custom/default/single
    partitioning: default

    disable_ipv6: true
    selinux: enforcing
    #fips_enable: true
    # NB. Not supported on RHEL 10+
    #security_profile: cis
    boot_parameters: net.ifnames.prefix=net quiet

    # hostname not used with ISO, set the ip= boot parameter instead
    ntp_servers: time.cloudflare.com
    timezone: Europe/Helsinki
    keyboard: fi

    create_admin: true
    admin_user:
      uid: 4444
      gid: 4444
      name: admin
      group: admin
      groups: wheel
      home: /home/admin
      gecos: Admin User
      #ssh_key: ssh-ed25519 ... admin@image
      passwordless_sudo: true

    root_permit_local: true
    root_permit_ssh: "prohibit-password"
    # NB. Not supported on RHEL 10+
    root_permit_override_security_policy: false
    #root_ssh_key: ssh-ed25519 ... root@image

    #
    # Builder configurations
    #

    # Builder: ISO (not a Packer builder)
    # Set ip= to create fully automated ISO for one particular server only
    # Use 'ip=' for generic ISO and require typing IP info on boot from ISO
    iso_boot_parameters: inst.geoloc=0 ip=192.168.122.123::192.168.122.1:255.255.255.0:server.example.com:net0:none
    output_directory: /tmp/iso_images

    # Apply boot config fix needed on UEFI with RHEL ISO
    # images booting from USB sticks. This requires sudo.
    iso_boot_usb_fix: false

    #
    # OS installer configuration
    #
    iso:
      rhel_8_10:
        url: file:///VirtualMachines/boot/rhel-8.10-x86_64-dvd.iso
        checksum: "none"
      rhel_9_5:
        url: file:///VirtualMachines/boot/rhel-9.6-x86_64-dvd.iso
        checksum: "none"
      rhel_10_0:
        url: file:///VirtualMachines/boot/rhel-10.0-x86_64-dvd.iso
        checksum: "none"

  roles:
    - myllynen.ansible_packer.ansible_packer
