---
namespace: myllynen
name: ansible_packer
version: "2.0.5"
readme: README.md
authors:
  - Marko Myllynen <myllynen@redhat.com>
description: >
  Ansible Packer Role for VM/ISO Image Creation.
license:
  - GPL-3.0-or-later
tags:
  - packer
  - build
  - image
  - rhel
  - centos
  - fedora
  - windows
dependencies:
  ansible.posix: ">=1.5.0"
repository: https://www.github.com/myllynen/ansible-packer
issues: https://www.github.com/myllynen/ansible-packer/issues
