---
__apc_base_target: "{{ packer_target.split('_')[0] }}"
__apc_base_version: "{{ packer_target.split('_')[1] }}"
__apc_full_version: "{{ packer_target.split('_')[1:] | join('_') }}"
__apc_target_config: "{{ __apc_base_target + '_' + __apc_base_version }}"
__apc_target_fullname: "{{ __apc_base_target + '_' + __apc_full_version }}\
                        {{ '' if security_profile is not defined else '_' + security_profile }}"
