---
__boot_pw_cleartext: "{{ boot_password | default('', true) | string }}"
__boot_pw_encrypted: "{{ '' if __boot_pw_cleartext == '' else lookup('pipe', 'printf \"' + __boot_pw_cleartext + '\n' + __boot_pw_cleartext + '\n\" | grub2-mkpasswd-pbkdf2').split(' ')[-1] }}"  # noqa: yaml[line-length]
__root_pw_cleartext: "{{ root_password | string }}"
#__root_pw_hash_algo: "{{ 'yescrypt' if __base_version | int >= 10 else 'sha512' }}"
__root_pw_hash_algo: "{{ 'sha512' }}"
__root_pw_encrypted: "{{ __root_pw_cleartext | password_hash(__root_pw_hash_algo) }}"
