---
__apc_boot_pw_cleartext: "{{ boot_password | default('', true) | string }}"
__apc_boot_pw_encrypted: "{{ '' if __apc_boot_pw_cleartext == '' else lookup('pipe', 'printf \"' + __apc_boot_pw_cleartext + '\n' + __apc_boot_pw_cleartext + '\n\" | grub2-mkpasswd-pbkdf2').split(' ')[-1] }}"  # noqa: yaml[line-length]
__apc_root_pw_cleartext: "{{ root_password | string }}"
# https://github.com/ansible/ansible/issues/75797
#__root_pw_hash_algo: "{{ 'yescrypt' if __apc_base_version | int >= 10 else 'sha512' }}"
__apc_root_pw_hash_algo: "{{ 'sha512' }}"
__apc_root_pw_encrypted: "{{ __apc_root_pw_cleartext | password_hash(__root_pw_hash_algo) }}"
