---
- name: Create Packer build file
  vars:
    __apc_win_str: "{{ '-win' if win_admin_password is defined else '' }}"
  ansible.builtin.template:
    src: build-{{ packer_builder }}{{ __apc_win_str }}.json.j2
    dest: "{{ __apc_tempdir.path }}/build.json"
    mode: '0600'

- name: Run Packer to build target image (this will take a while)
  no_log: "{{ packer_build_no_log }}"
  ansible.builtin.shell: |
    cd {{ __apc_tempdir.path }}
    export PACKER_LOG=1
    export CHECKPOINT_DISABLE=1
    export TMPDIR="{{ __apc_tempdir.path }}"
    export ANSIBLE_ROLES_PATH="{{ win_provisioner_role_path | default('roles', true) }}"
    export VCENTER_PASSWORD='{{ vcenter_credentials.vcenter_password | default("", true) }}'
    export WIN_ADMIN_PASSWORD='{{ win_admin_password | default("", true) }}'
    {{ packer_binary }} build -color=false {{ '-force' if use_force | bool else '' }} build.json
  register: __apc_packer_result
  failed_when: "'successful build' not in __apc_packer_result.stdout"
  changed_when: true

- name: Display Packer command output
  ansible.builtin.debug:
    var: __apc_packer_result.stdout
