---
- name: Create Packer build file
  vars:
    win_str: "{{ '-win' if win_winrm_password is defined else '' }}"
  template:
    src: build-{{ packer_builder }}{{ win_str }}.json.j2
    dest: "{{ tempdir.path }}/build.json"
    mode: '0600'

- name: Run Packer to build target image (this will take a while)
  shell: |
    cd {{ tempdir.path }}
    export PACKER_LOG=1
    export CHECKPOINT_DISABLE=1
    export TMPDIR="{{ tempdir.path }}"
    export VCENTER_PASSWORD='{{ vcenter_credentials.vcenter_password | default("", true) }}'
    export WIN_WINRM_PASSWORD='{{ win_winrm_password | default("", true) }}'
    {{ packer_binary }} build -color=false {{ '-force' if use_force | bool else '' }} build.json
  no_log: "{{ packer_build_no_log }}"
  register: packer_result
  failed_when: "'successful build' not in packer_result.stdout"
  changed_when: true

- name: Display Packer command output
  debug:
    var: packer_result.stdout
