---
# https://www.packer.io/docs/builders/vsphere/vsphere-iso
#vcenter_credentials:
#  vcenter_server:
#  vcenter_username:
#  vcenter_password:
vcenter_insecure_connection: false

vcenter_datacenter:
vcenter_folder:

# https://www.packer.io/docs/builders/vsphere/vsphere-iso#working-with-clusters-and-hosts
#vcenter_host:
vcenter_cluster:

#vcenter_resource_pool:

vcenter_datastore:
vcenter_network:

vm_guest_os_type: "{{ __base_target.split('-')[0] + __base_version }}_64Guest"

# https://www.packer.io/plugins/builders/vsphere/vsphere-iso#content-library-import-configuration
vcenter_convert_to_template: true
#vcenter_content_library:
#  library:
#  #name:
#  ovf:
#  destroy:
