---
# https://www.packer.io/plugins/builders/qemu#boot-configuration
boot_wait: 10s

# The OS installer boot_command will be appended by boot_parameters and boot_start
# RHEL-compatible boot_command on BIOS
#boot_command: <up><wait><tab><wait> inst.ks=hd:/dev/sr1:/inst.cfg inst.geoloc=0 inst.nosave=all ip=dhcp
# RHEL-compatible boot_command on UEFI
boot_command: <up><wait>e<wait><down><down><leftCtrlOn>e<leftCtrlOff> inst.ks=cdrom:/inst.cfg inst.geoloc=0 inst.nosave=all ip=dhcp

# Custom boot parameters to append
boot_parameters: net.ifnames.prefix=net quiet

# NB. With RHEL on BIOS use '<enter>' to boot, on UEFI must use '<leftCtrlOn>x<leftCtrlOff>'
boot_start: <leftCtrlOn>x<leftCtrlOff><wait>

boot_password:
#root_password:

# Autopartitioning does not support
# creating BIOS/UEFI-compatible images
# NB. RHEL 10+ is UEFI only
bios_uefi_boot: true
# One of: auto/custom/default/single
#partitioning:
disable_ipv6: false
selinux: enforcing
fips_enable: false
# NB. Not supported on RHEL 10+
#security_profile:

serial_console_setup: false
kdump_update_disable: false

# Ask installer to setup DHCP networking for the image
network_setup_dhcp: true
# Remove static network configuration setup by installer
network_setup_purge: true

hostname: localhost.localdomain
ntp_servers: time.cloudflare.com
timezone: UTC
keyboard: us

install_single_lang: true
install_exclude_docs: false
install_exclude_weak_deps: false

create_admin: false
#admin_user:
#  uid: 4444
#  gid: 4444
#  name: admin
#  group: admin
#  groups: wheel
#  gecos: Admin User
#  ssh_key: ssh-ed25519 ... admin@image
#  passwordless_sudo: false

root_permit_local: true
root_permit_ssh: "prohibit-password"
# NB. Not supported on RHEL 10+
root_permit_override_security_policy: false
#root_ssh_key: "ssh-ed25519 ... root@image"

# Define to temporarily register and update RHEL
# To be replaced with rhsm directive once available
#rh_register_command:
# Install Satellite tools when updating packages
rh_satellite_tools_install: true

#custom_partitioning: |
#  reqpart
#  part /boot    --fstype xfs      --size 1024 --grow
#  part /        --fstype xfs      --size 1024 --grow
#  part swap     --fstype swap     --size 2048

#custom_packages: |
#  cloud-init
#  cloud-utils-growpart
#  insights-client
#  rhc
#  rhc-worker-playbook
#  sos
#  unzip

#custom_section_early: |
#  %post --erroronfail
#  cat /etc/resolv.conf > /var/tmp/.inst-resolv-conf
#  %end

#custom_section_late: |
#  %post --erroronfail
#  touch /.unconfigured
#  %end
