---
do_cleanup: true
use_force: false

packer_binary: packer.io

# Set no_log when running Packer, should be set if
# using password for vCenter or WinRM after tests
packer_build_no_log: false

communicator: "none"

# Timeout for Packer VM installation
shutdown_timeout: 15m

# Example Packer Ansible provisioner conf for RHEL
#
#communicator: "ssh"
#
## Needs to have root_permit_ssh set accordingly
#custom_json_builder_section: |
#  "pause_before_connecting": "10s",
#  "ssh_timeout": "15m",
#  "ssh_username": "root",
#  "ssh_private_key_file": "{{ ssh_private_key_file }}",
#
#custom_json_provisioner: |
#  {
#    "type": "ansible",
#    "use_proxy": false,
#    "playbook_file": "/tmp/rhel_packer.yml",
#    "user": "admin"
#  }
