---
do_cleanup: true
use_force: false

packer_binary: packer.io

# Set no_log when running Packer, should be set if
# using password for vCenter or WinRM after tests
packer_build_no_log: false

communicator: "none"

# Timeout for Packer VM installation
shutdown_timeout: 15m

# Example Packer Ansible provisioner conf for RHEL
# NB. Writes cleartext root password in build.json
#
#communicator: "ssh"
#
## Needs to have root_permit_ssh set accordingly
#custom_json_builder_section: |
#  "ssh_username": "root",
#  "ssh_password": "{{ image_password }}",
#  "ssh_timeout": "15m",
#
#custom_json_provisioner: |
#  {
#    "type": "ansible",
#    "use_proxy": false,
#    "playbook_file": "/tmp/rhel_packer.yml",
#    "user": "admin"
#  }
