---
# https://www.packer.io/plugins/builders/qemu#boot-configuration
win_boot_wait: 3s
# Must be set when using UEFI, use '<enter>' on BIOS
win_boot_command: <enter>FS1:<enter>EFI\\BOOT\\bootx64.efi<enter>

# Full path for additional drivers for the target Windows version
# For QEMU/KVM example, see the virtio-win-drivers-prepare script
# https://fedorapeople.org/groups/virt/virtio-win/direct-downloads/stable-virtio/virtio-win.iso
#win_drivers_path:

# Windows OS edition to install from the ISO
# Interactive installation will show editions
# The index reference should be either INDEX or NAME
win_os_index: INDEX
win_os_edition: 1

# Windows ISO label
win_iso_volume_id: WINDOWS_ISO

# Disk drive definitions: PowerShell scripts, Windows installer, VM tools
win_pss_disk: "{{ 'A:' if packer_builder == 'vmware' else 'E:' }}"
win_src_disk: "{{ win_pss_disk if packer_builder != 'iso' else 'D:' }}"
win_vm_tools_disk: "{{ 'E:' if packer_builder == 'vmware' else win_src_disk }}"

# Either bios, uefi, or custom
# See below for custom example
win_partitioning: uefi

win_timezone: UTC

# System locale setting
win_locale_system: en-US
# UI locale setting
win_locale_ui: en-US
# User locale setting
win_locale_user: en-US
# Input locale (language and keyboard) setting, see
# https://learn.microsoft.com/en-us/windows-hardware/manufacture/desktop/default-input-locales-for-windows-language-packs
win_locale_input: 0409:00000409

# Password for Windows Administrator and remote management
# account that will be created during installation, see below.
# NB! This variable is used to determine whether to build RHEL
#     or Windows ISOs/VMs and for building RHEL must be unset.
#win_admin_password:

#win_product_key:
#win_registered_owner:
#win_registered_organization:

#win_custom_partitioning_create: |
#    <CreatePartition wcm:action="add">
#        <Order>1</Order>
#        <Type>Primary</Type>
#        <Extend>true</Extend>
#    </CreatePartition>

#win_custom_partitioning_modify: |
#    <ModifyPartition wcm:action="modify">
#        <Order>1</Order>
#        <PartitionID>1</PartitionID>
#        <Label>Windows</Label>
#        <Format>NTFS</Format>
#        <Letter>C</Letter>
#    </ModifyPartition>

#win_custom_partitioning_install_to: 1

# Customization script, runs before enabling remote access
#win_customize_script: |
