---
# Remote management account name
win_remote_user: winrm

# Optional administrators SSH key to install
#win_admin_ssh_key:

# Setup SSH for remote access
win_remote_setup_ssh: |
  Get-NetConnectionProfile | Set-NetConnectionProfile -NetworkCategory Private
  $missing = Get-WindowsCapability -Name 'OpenSSH.Server*' -Online | ? State -ne 'Installed'
  if ($missing) {
    Add-WindowsCapability -Name $missing.Name -Online
  }
  Start-Service -Name sshd
  Set-Service -Name sshd -StartupType Automatic
  Set-ItemProperty -Path HKLM:\SOFTWARE\OpenSSH -Name DefaultShell -Value C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe
  if (!(Get-NetFirewallRule -Name OpenSSH-Server-In-TCP | Select-Object -Property Name, Enabled)) {
    New-NetFirewallRule `
      -Enabled True `
      -Name OpenSSH-Server-In-TCP `
      -DisplayName 'OpenSSH SSH Server (sshd)' `
      -Description 'Inbound rule for OpenSSH SSH Server (sshd)' `
      -Group 'OpenSSH Server' `
      -LocalPort 22 `
      -Action Allow `
      -Direction Inbound `
      -Protocol TCP `
      -Profile @('Domain', 'Private')
  }
  $keyFile = 'C:\ProgramData\ssh\administrators_authorized_keys'
  $publicKey = '{{ win_admin_ssh_key | default("", true) }}'
  if (!(Test-Path -Path $keyFile)) {
    New-Item -Path $keyFile -ItemType File
  }
  icacls.exe $keyFile /inheritance:r /grant ""Administrators:F"" /grant ""SYSTEM:F""
  if ($publicKey.StartsWith('ssh')) {
    Add-Content -Path $keyFile -Value $publicKey
  }

# Setup WinRM for remote access
win_remote_setup_winrm: |
  Get-NetConnectionProfile | Set-NetConnectionProfile -NetworkCategory Private
  Start-Service -Name WinRM
  Set-Service -Name WinRM -StartupType Automatic

  $user = '{{ win_remote_user }}'
  $sid = (New-Object -TypeName System.Security.Principal.NTAccount -ArgumentList $user).Translate([System.Security.Principal.SecurityIdentifier])
  $sddl = (Get-Item -Path WSMan:\localhost\Service\RootSDDL).Value
  $sd = New-Object -TypeName System.Security.AccessControl.CommonSecurityDescriptor -ArgumentList $false, $false, $sddl
  $sd.DiscretionaryAcl.AddAccess(
    [System.Security.AccessControl.AccessControlType]::Allow,
    $sid,
    [int]0x10000000,
    [System.Security.AccessControl.InheritanceFlags]::None,
    [System.Security.AccessControl.PropagationFlags]::None
    )
  $sddl = $sd.GetSddlForm([System.Security.AccessControl.AccessControlSections]::All)
  Set-Item -Path WSMan:\localhost\Service\RootSDDL -Value $sddl -Force

  Set-Item -Path WSMan:\localhost\Service\AllowUnencrypted -Value $false
  Set-Item -Path WSMan:\localhost\Service\Auth\Basic -Value $true
  Set-ExecutionPolicy -ExecutionPolicy RemoteSigned
  $friendlyName = 'WinRM over HTTPS'
  $cert = New-SelfSignedCertificate -CertStoreLocation Cert:\LocalMachine\My `
            -DnsName $env:COMPUTERNAME -NotAfter (get-date).AddYears(10) `
            -Provider 'Microsoft Enhanced RSA and AES Cryptographic Provider' `
            -KeyLength 4096
  $cert.FriendlyName = $friendlyName
  New-Item -Path WSMan:\localhost\Listener -Transport HTTPS `
    -Address * -CertificateThumbPrint $cert.Thumbprint -Force
  if (!(Get-NetFirewallRule -Name WINRM-HTTPS-In-TCP -ErrorAction SilentlyContinue | Select-Object -Property Name, Enabled)) {
    New-NetFirewallRule `
      -Enabled True `
      -Name WINRM-HTTPS-In-TCP `
      -DisplayName 'Windows Remote Management (HTTPS-In)' `
      -Description 'Inbound rule for Windows Remote Management via WS-Management. [TCP 5986]' `
      -Group '@FirewallAPI.dll,-30267' `
      -LocalPort 5986 `
      -Action Allow `
      -Direction Inbound `
      -Protocol TCP `
      -Profile @('Domain', 'Private')
  }

# Remote access method to configure
# By default both SSH and WinRM are enabled
win_remote_setup: |
  {{ win_remote_setup_ssh }}

  {{ win_remote_setup_winrm }}
